### ISSUE TITLE
Migrate to GitLab

### ISSUE THREAD

**Issue by brlin-tw** [brlin-tw/.profile.d#3]
GitLab is now the preferred project hosting platform for my projects, this repository will instead become a mirror for disaster recovery purposes.

## Subtasks

* [ ] Import the project to GitLab(currently blocked by the lack of GitHub functionality bug)
* [ ] Disable Issues/Projects/Wiki functionality on GitHub
* [ ] Update references to the project
